# Generated by Django 3.2.25 on 2024-04-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0002_nota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='color',
            field=models.CharField(choices=[('#ff0000', 'Rojo'), ('#00ff00', 'Verde'), ('#0000ff', 'Azul')], default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='nota',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='notas_imagenes/'),
        ),
    ]
