# Generated by Django 3.2.25 on 2024-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0003_auto_20240417_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='color',
            field=models.CharField(blank=True, choices=[('#ff0000', 'Rojo'), ('#00ff00', 'Verde'), ('#0000ff', 'Azul')], default='#ffffff', max_length=20, null=True),
        ),
    ]
