# Generated by Django 4.2.4 on 2024-04-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablero', '0004_alter_nota_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='color',
            field=models.CharField(blank=True, choices=[('#EA9E19', 'Amarillo'), ('#54ea19', 'Verde'), ('#19b6ea', 'Azul')], default='#ffffff', max_length=20, null=True),
        ),
    ]
